# Generated by Django 3.1.1 on 2020-10-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_bill', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_mobile', models.CharField(max_length=12)),
                ('customer_village', models.CharField(max_length=50)),
                ('customer_paid_bal', models.CharField(max_length=100)),
                ('customer_due_bal', models.CharField(max_length=200)),
                ('customer_total_bal', models.CharField(max_length=20)),
            ],
        ),
    ]
