# Generated by Django 3.1.1 on 2020-10-05 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='modi_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
