# Generated by Django 3.1.1 on 2020-10-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_auto_20201005_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='modi_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
